config/routes.rb
Inzomb::Application.routes.draw do

  get "beta/index"

  post "image/new_comment" => "image#new_comment"

  post "beta/validate"

  get "image/index"
  post "image/new" => "image#create"
  get "image/upvote" => "image#upvote"
  get "image/downvote" => "image#downvote"
  get "image/flagPicture" => "image#flagPicture"
  get "image/votes" => "image#votes"
  get "image/new"
  get "sessions/new"

  get "users/new"

  get "upload" => "image#new", :as => "upload"

  get "images" => "image#index", :as => "images"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "profiles/:username" => "users#profiles"

  root :to => "beta#index" #:to => "image#index"
  resources :users
  resources :sessions
  resources :image

  resources :beta

end

app/models/beta_user.rb
class BetaUser < ActiveRecord::Base
  def self.validateBetaUser(firstName, lastName)
    self.where(:FirstName => firstName.downcase , :LastName => lastName.downcase).first
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :images, :foreign_key => :image_id

  validates_presence_of :user_id, :image_id, :comment_text


end

app/models/image_flag.rb
class ImageFlag < ActiveRecord::Base
  belongs_to :images, :foreign_key => :image_id
  belongs_to :user, :foreign_key => :user_id
end

app/models/images.rb
class Images < ActiveRecord::Base
  belongs_to :user
  has_many :votes, :foreign_key => :image_id
  has_many :comments, :foreign_key => :image_id

  accepts_nested_attributes_for :comments
  validates_attachment_presence :image
  validates_attachment_size :image, :in => 1..3000000


  has_attached_file :image,
    :styles => { :thumb => "100x100#", :thumb2 => "200x200#", :large => "1000x1000#"},
    :storage => :s3,
      :s3_credentials => S3_CREDENTIALS,
      :path => ":attachment/:id/:style.:extension"

  def vote_exists(user)
    upvote_exists(user) || downvote_exists
  end
  def upvote_exists(user)
    return false if user.nil?
    self.votes.exists?(:user_id => user.id, :upvote => true)
  end

  def downvote_exists(user)
    return false if user.nil?
    self.votes.exists?(:user_id => user.id, :upvote => false)
  end

  def upvote
    self.upscore += 1
    self.save
  end
  def downvote
    self.downscore -= 1
    self.save
  end
  def score
    self.upscore
  end
  def self.ten_most_recent
    return order("created_at desc").limit(10)
  end
  def self.ten_most_votes
    return order("upscore desc").limit(10)
  end
  def recent_comments
    return self.comments.order("created_at desc").limit(5)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :images
    has_many :votes, :foreign_key => :image_id
    has_many :comments, :foreign_key => :image_id

    attr_accessible :name, :email, :password, :password_confirmation

    attr_accessor :password
    before_save :encrypt_password

    validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :name
    validates_uniqueness_of :name
    validates_uniqueness_of :email, :unless => Proc.new {|a| a.email.blank?}

    def self.authenticate(name, password)
      user = find_by_name(name)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end

    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user, :foreign_key => :user_id
  belongs_to :images, :foreign_key => :image_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper :all

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  @home =  {:controller => :image, :action => :index}
end

app/controllers/beta_controller.rb
class BetaController < ApplicationController
  def index
    render :layout => false
  end

  def validate
    firstName = params[:first_name]
    lastName = params[:last_name]

    user = BetaUser.validateBetaUser(firstName, lastName)
    if(user)
      user.HasLoggedIn = true
      user.save
      redirect_to :controller => 'image', :action => 'index'
    else
      redirect_to('/access_denied.html')
    end

  end

  def new
    @beta = BetaUser.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show

  end

  def update
  end

  def index

  end

  def create

  end
  def new
    @comment = Comment.new
  end

end

app/controllers/image_controller.rb
class ImageController < ApplicationController
  before_filter :authenticate, :except => [:index, :votes, :recent]
  
  def authenticate
    if !current_user
      redirect_to :controller => :sessions, :action => :new, :notice => "Please login before uploading image"
    end
  end
  
  def index
    recent
  end
  def recent
    if current_user.nil?
      @logged = false
    end
    @category = :recent
    @images = Images.ten_most_recent
    @comment = Comment.new
  end
  def new_comment
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to :action => :index, :notice => "Comment successful"
    else
    end
  end
  def votes
    @category = :votes
    @images = Images.ten_most_votes
    render :index
  end  
  def upvote
    image = Images.find_by_id(params[:id])
    image.upvote
    Vote.create!( :user => current_user, :images => image, :upvote => true)
    redirect_to images_path
  end
  def flagPicture
    image = Images.find_by_id(params[:id])
    UserMailer.flagPicture(image, current_user).deliver
    redirect_to images_path
  end
  def downvote
    image = Images.find_by_id(params[:id])
    image.downvote
    Vote.create!( :user => current_user, :images => image, :upvote => false)
    redirect_to images_path
  end
  def create
    @image = Images.new(params[:image])
    @image.user_id = current_user.id
    @image.upscore = 0
    @image.downscore = 0
    if @image.save
      redirect_to :action => :index, :notice => "Image Successfully Uploaded"
    else
      render "new"
    end
    
  end
  def new
    @image = Images.new
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  def create
    user = User.authenticate(params[:name],params[:password])
    if user
      session[:user_id] = user.id
      redirect_to "/image/index", :notice => "Logged in"
    else
      flash[:error] = "Invalid username or password"
      render "new", :notice => "Invalid username or password"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to "/image/index", :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def index
    @users = User.all
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to  "/image/new", :notice => "Thanks for signing up!"
    else
      render "new"
    end
  end
  def profiles
    @user = User.find_by_name(params[:username])
    if @user
      @images = Vote.where(:user_id => @user.id).limit(10).order("created_at desc").collect {|x| x.images }
    else
      redirect_to :controller => :image, :action => :index, :notice => "Invalid User Profile"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_link(user)
    link_to( user.name, "/profiles/#{user.name}" )
  end
end

app/helpers/beta_controller_helper.rb
module BetaControllerHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beta/index.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" class="no-js">
<head>
  <!-- (c) Copyright 2012, Instagram, Inc  -->

  <meta charset="UTF-8" />
  <title>Inzomb Beta • Coming soon!</title>
  <link rel="Shortcut Icon" type="image/x-icon" href="favicon.ico" />

  <style>@import "index.css";</style>

  <!--[if lt IE 9]>

  <style type="text/css">

      .overlay {
          display: none !important;
      }
  </style>

  <![endif]-->
<head>
  <%= form_tag({:controller => "beta", :action => "validate"}, :method => "post") do %>
      <div id='label'>
      <%= label_tag 'First Name' %>
      <%= text_field_tag("first_name", "")  %>
      </div>
      <%=label_tag 'Last Name'  %> <%=text_field_tag("last_name", "") %>  <BR>

      <%= submit_tag("Submit") %>
  <% end  %>

  <title>Landing page</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <style type="text/css">
      body {
          background-image: url('/assets/retro_rainbow-wallpaper-1440x900.jpg');
          background-repeat: no-repeat;
      }
      .test {
          font-family: Arial, Helvetica, sans-serif;
      }
      .test {
          font-family: Arial, Helvetica, sans-serif;
      }
      .test {
          font-family: Arial, Helvetica, sans-serif;
      }
      body,td,th {
          color: #FFF;
          font-family: Arial, Helvetica, sans-serif;
          font-size: 14px;
      }
      .test {
          font-family: Arial, Helvetica, sans-serif;
      }

  </style>
</head>

app/views/beta/old.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" class="no-js">
<head>
  <!-- (c) Copyright 2012, Instagram, Inc  -->

  <meta charset="UTF-8" />
  <title>Inzomb Beta • Coming soon!</title>
  <link rel="Shortcut Icon" type="image/x-icon" href="favicon.ico" />

  <style>@import "index.css";</style>

  <!--[if lt IE 9]>

  <style type="text/css">

      .overlay {
          display: none !important;
      }
  </style>

  <![endif]-->
<head>

  <title>Landing page</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <style type="text/css">
      body {
          background-image: url('/assets/retro_rainbow-wallpaper-1440x900.jpg');
          background-repeat: no-repeat;
      }
      .test {
          font-family: Arial, Helvetica, sans-serif;
      }
      .test {
          font-family: Arial, Helvetica, sans-serif;
      }
      .test {
          font-family: Arial, Helvetica, sans-serif;
      }
      body,td,th {
          color: #FFF;
          font-family: Arial, Helvetica, sans-serif;
          font-size: 14px;
      }
      .test {
          font-family: Arial, Helvetica, sans-serif;
      }
  </style>
</head>

<body>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;		</p>
<p>
  <?php
&first name = ["firstname"];
&last name = ["lastname"];

if ($username == "admin" && $password == "admin") {
	echo "Logged In"};

?>

</p>


    <form name="form1" method="post" action="">
  <p align="center"><strong>inzomb</strong></p>
  <p align="center"><strong>Welcome to the beta. </strong></p>
  <p align="center"><span class="test"><strong>First Name</strong></span>
    <input type="text" name="First name" id="First name">
  </p>
  <p align="center"><span class="test"><strong>Last</strong></span><strong> <span class="test">Name</span></strong>
    <input type="text" name="Last name" id="Last name">
  </p>
  <p align="center">
    <input type="submit" name="Enter" id="Enter" value="Enter">
  </p>
</form>
</body>

<meta name="viewport" content="initial-scale=1, maximum-scale=1" />

<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-18105282-1']);
    _gaq.push(['_setDomainName', 'instagr.am']);
    _gaq.push(['_trackPageview']);
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body>

<div class="page-wrapper">
  <header>
    <h1>Inzomb</h1>

    <p>Coming soon!</p>
  </header>


  <p class="form-text">

  </p><p class="form-actions">

</p>

  <p class="notice positive" style="display:none">
    Thanks for signing up! We'll be in touch soon!
  </p>

  <p class="notice negative" style="display:none">
    It seems that something went wrong! </br>
    Did you enter a correct e-mail address?
  </p>
  </fieldset>
  </form>
  <footer>

    <p class="legal"><span>beta.inzomb.com</a></p>
  </footer>
</div>

<div class="overlay"></div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function(){
        var is_ios = (
                        (navigator.userAgent.toLowerCase().indexOf("ipad") > -1) ||
                                (navigator.userAgent.toLowerCase().indexOf("iphone") > -1) ||
                                (navigator.userAgent.toLowerCase().indexOf("ipod") > -1)),
                is_opera = (navigator.userAgent.toLowerCase().indexOf("opera") > -1);

        setTimeout(function(){
            // Hide the address bar!
            window.scrollTo(0, 1);
        }, 0);

        if (is_ios) {
            $('body').addClass('ios');
        }

        // Add no-anim class to prevent reanimating
        if (is_opera) {
            $('body').addClass('no-anim');
        } else {
            setTimeout(function() {
                $('body').addClass('no-anim');
            }, 5000);
        }

        // Hide all notices
        $('.notice').hide();

        // Handle form submit
        $('#email-form').submit(function(event) {
            event.preventDefault();

            var $form = $(this),
                    $email_field = $form.find('input[name="email"]'),
                    email = $email_field.val()
            url = $form.attr('action');

            // Do not submit if email is empty
            if ($.trim(email).length == 0) {
                return;
            }

            $.post(url, { email: email },
                    function(data) {
                        $email_field.val('').blur();
                        $('.form-text,.form-actions').hide();
                        $('.notice.positive').fadeIn();
                        $('.notice.negative').hide();
                    }
                    , 'json')
                    .error(function(data) {
                        $('.notice.positive').hide();
                        $('.notice.negative').fadeIn();
                    });
        });
    });
</script>
</body>
</html>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/image/index.html.erb
<div id="categories">
	<%= link_to_unless_current "Most Recent", images_path %> |
	<%= link_to_unless_current "Top Votes", :controller => :image, :action => :votes %>
</div>
<% @images.each do |image| %>
    <div id='image_post'>
      <div id='voting_layout' class="halign">
          <% if image.upvote_exists(current_user) %>
              <%= image_tag("up_voted.png") %>
                <br>  &nbsp;  <font size="5"> <%= image.upscore + image.downscore %> </font>  <br>
                <%= image_tag("down_arrow.png") %>
          <% elsif image.downvote_exists(current_user) %>
                <%= image_tag("up_arrow.png") %>
                <br>  &nbsp;  <font size="5"> <%= image.upscore + image.downscore %> </font>  <br>
                <%= image_tag("down_voted.png") %>
          <% else %>
                <%= link_to image_tag("up_arrow.png", :mouseover => "up_voted.png"), {:action => :upvote, :id => image.id} %>
                <br>  &nbsp;  <font size="5"> <%= image.upscore + image.downscore %> </font>  <br>
                <%= link_to image_tag("down_arrow.png", :mouseover => "down_voted.png"), {:action => :downvote, :id => image.id} %>
          <% end %>
            <div id='flagging_layout'>
            <br> <font size="2"><%=  link_to "Report",{:action => :flagPicture, :id => image.id}  %> </font>   <br>
            </div>
         </div>
      </div>
      <div id='image_post' class="halign">

	<span id='image_top'>
		<span id='image_username'>
			<%= profile_link(image.user) %>
		</span>
		<span id='image_caption'>
			<%= image.caption %>
		</span>
	</span>
	<div id='image_square' class='image_resizer'>
		<%= link_to(image_tag(image.image.url(:large)), image.image.url ) unless image.image.nil? %>
      <span id='image_time'>
      		Posted <%= time_ago_in_words(image.created_at) %> ago.
      	</span>
	</div>
    <div id="comments">
      <% if !current_user.nil? %>
      <div id='new_comment'>
        <%=  form_for @comment, :url => {:action => :new_comment} do |f| %>
            <%= f.text_field :comment_text %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :image_id, :value => image.id %>
            <%= f.submit "Comment" %>
        <% end %>

      </div>
       <% end %>
        <%  image.recent_comments.each do |comment| %>
        <div id='comment'>

            <div id='comment_top'><span id='comment_username'><%=   profile_link(comment.user) %></span><span id='comment_time'><%=  time_ago_in_words(comment.created_at) %></span></div>

            <div id='comment_text'><%=  comment.comment_text %></div>
        </div>
        <% end %>
    </div>
</div>
<br>
<% end %>

app/views/image/new.html.erb
<div id='signup'>
<%= form_for :image, :html => { :multipart => true } do |image| %>
<% if @image.errors.any? %>
    <div class="error_messages">
      <h2>Uh oh!</h2>
      <ul>
        <% for message in @image.errors.full_messages %>
          -<%= message %><br>
        <% end %>
      </ul>
    </div>
  <% end %>
Choose Image: <%= image.file_field :image %><br>
Caption:<br> <%= image.text_field :caption %><br>
<p class="button"><%= image.submit %></p>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inzomb </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body onclick = 'TopUp.close()' >

<div id="banner">
  <span id="banner_image"> <%= image_tag "banner2.PNG" %>   </span>
  <%= render 'shared/navbar' %>
</div>
        <div id="main">
		<div id="content">
			<%= yield %>
		</div>
	</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<div id="navbar_right">

  		<% if current_user %>
    		<span id='image_username'><%= profile_link(current_user) %></span> |
    		<%= link_to "Logout", logout_path %> |
			<%= link_to "Upload Image", upload_path %>
  		<% else %>
    		<%= link_to "Signup", signup_path %> |
    		<%= link_to "Login", login_path %>
  		<% end %>

</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= 	user.name %><br>
<% end %>

app/views/users/new.html.erb
<div id="signup">
<h1>Signup</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Uh oh!</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          -<%= message %><br>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  
    <p><%= f.label :name, "Name "%><br>
    <%= f.text_field :name %></p>

    <p><%= f.label :password, "Password" %><br>
    <%= f.password_field :password %></p>
  
	
    <p><%= f.label :password_confirmation, "Retype Password"%><br>
    <%= f.password_field :password_confirmation %></p>
	
  
    <p><%= f.label :email %><br>
    <%= f.email_field :email %></p>

  <p class="button"><%= f.submit %></p>
<% end %>
</div>

app/views/users/profiles.html.erb
<div id="profile_content">
	<div id="profile_left">
		<div id="profile_likes">
			<h2>Recently Liked Images</h2>
			<% @images.each do |image| %>
				<%= link_to(image_tag(image.image.url(:thumb)), image.image.url ) %>
			<% end %>
		</div>
	</div>
	<div id="profile_right">
		<span id="profile_username"><%= @user.name %></span>
		<div id="profile_user">
		</div>
	</div>
</div>